site_name: Data With Logan
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    # - navigation.path
    # - navigation.expand
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.tabs.sticky
    # - toc.integrate
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    # - content.code.annotation
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.tooltips
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: amber
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: amber
extra_css: 
    - css/extra.css
extra_javascript:
    - css/footer.js

nav:
  - Home: index.md
  - dbt:
    - dbt/index.md
    # - Architecture:
    # - Deployment:
    # - Tips & Tricks:
  - Snowflake: 
    - snowflake/index.md
    - Cost Optimization: 
      - snowflake/cost_optimization/index.md
      - Warehouse Sizing: snowflake/cost_optimization/1.warehouse_sizing.md
      - Incremental Materialization: snowflake/cost_optimization/2.incremental_materialization.md
      - Snowflake Stream: snowflake/cost_optimization/3.snowflake_stream.md
      - Update & Delete Principal: snowflake/cost_optimization/4.update_and_delete_principal.md
  - Dagster:
    - dagster/index.md
    - Overview: dagster/1.overview.md
    - Setting Up: dagster/2.setting_up.md
    - Deployment: dagster/3.deployment.md
    # - Tips & Tricks:
      
plugins:
  - glightbox
#     - encryptcontent:
#         global_password: 'abc'
#         title_prefix: ''
#         summary: 'Encrypted content'
#         placeholder: 'Enter your password'
#         decryption_failure_message: 'Wrong password!'
#         encryption_info_message: 'Please contact me for password !'
#         input_class: 'md-search__form md-search__input'
#         button_class: 'md-search__icon'

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bao-long-tran/

copyright: |
  &copy; 2024 <a href="https://github.com/logantran26/" target="_blank" rel="noopener">Logan Tran</a>